import type { ViewerData, ViewerState } from "./types.js";

export function createViewerState(DATA: ViewerData): ViewerState {
    const nodes = DATA.nodes;
    return {
      homeRoot: DATA.rootId,
      currentRoot: DATA.rootId,
      theme: "github-light",
      metric: DATA.defaultMetric,
      weightedVariableWeight: 1,
      weightedNetWeight: 0.15,
      layoutMode: DATA.defaultMetric === "weighted_signals" || DATA.defaultMetric === "signals"
        ? "accurate"
        : "classic",
      decomposition: "subtree",
      analysisMode: "none",
      analysisPatternMode: "wildcard",
      analysisPattern: "",
      analysisError: "",
      analysisLocalCounts: new Array<number>(nodes.length).fill(0),
      analysisSubtreeCounts: new Array<number>(nodes.length).fill(0),
      analysisLocalLocs: new Array<number>(nodes.length).fill(0),
      analysisSubtreeLocs: new Array<number>(nodes.length).fill(0),
      analysisLocalRatios: new Array<number>(nodes.length).fill(0),
      analysisSubtreeRatios: new Array<number>(nodes.length).fill(0),
      analysisMaxSubtreeCount: 0,
      analysisVisibleMaxCount: 0,
      analysisVisibleMaxLoc: 0,
      analysisVisibleMaxRatio: 0,
      analysisVisibleSubtreeQualified: new Array<boolean>(nodes.length).fill(false),
      analysisLegendFilter: [],
      analysisLegendVisibleSubtree: new Array<boolean>(nodes.length).fill(false),
      analysisHatchDisabledUntil: 0,
      advancedPopoverOpen: false,
      advancedPopoverLeft: null,
      advancedPopoverTop: null,
      draggingAdvancedPopover: false,
      advancedPopoverDragOffsetX: 0,
      advancedPopoverDragOffsetY: 0,
      toolbarCollapsed: false,
      selectMode: false,
      depthLimit: null,
      zoom: 1,
      viewX: 0,
      viewY: 0,
      areas: [],
      hoverId: null,
      hoverAreaKind: "node",
      hoveredTreemapToggleId: null,
      treemapToggleTooltipNodeId: null,
      treemapToggleTooltipClientX: 0,
      treemapToggleTooltipClientY: 0,
      selectedId: null,
      selectedAreaKind: "node",
      hoverCardActive: false,
      hoverCardLeft: null,
      hoverCardTop: 18,
      draggingHoverCard: false,
      hoverCardDragOffsetX: 0,
      hoverCardDragOffsetY: 0,
      hoverUpdateTimer: null,
      selectClickTimer: null,
      sourceNodeId: null,
      sourceTargetKind: "instance",
      search: "",
      filterScope: "both",
      filterMode: "text",
      searchError: "",
      matches: [],
      matchIds: new Set(),
      matchVisibleIds: new Set(),
      matchSubtreeIds: new Set(),
      matchLines: [],
      sourceRequestToken: 0,
      sourceAbortController: null,
      sourcePanelFullscreen: false,
      sourceSearchMode: "wildcard",
      sourceSearch: "",
      sourceSearchError: "",
      sourceSearchMatchIndex: -1,
      sourceBookmarkEditingKey: null,
      sourceBookmarkEditingLine: null,
      sourceBookmarkEditingDraft: "",
      sourceBookmarksByFile: {},
      searchHistoryByField: {},
      treePanelOpen: false,
      treePanelWidth: 360,
      draggingTreePanelResize: false,
      treePanelResizeStartX: 0,
      treePanelResizeStartWidth: 360,
      matchPanelOpen: false,
      treeCollapsedIds: new Set(),
      matchPanelWidth: 360,
      matchPanelHeight: 480,
      matchPanelLeft: null,
      matchPanelTop: 12,
      draggingMatchPanel: false,
      matchPanelDragOffsetX: 0,
      matchPanelDragOffsetY: 0,
      draggingMatchPanelResizeX: false,
      draggingMatchPanelResizeY: false,
      matchPanelResizeStartX: 0,
      matchPanelResizeStartY: 0,
      matchPanelResizeStartWidth: 360,
      matchPanelResizeStartHeight: 480,
      treePanelDirty: true,
      matchPanelDirty: true,
      mainViewMode: "treemap",
      chartPanelOpen: false,
      chartMode: "weighted_bits",
      chartRenderMode: "pie2d",
      chartLevel: null,
      chartPanelDirty: true,
      zenMode: false,
      zenOverlayLeft: null,
      zenOverlayTop: null,
      draggingZenOverlay: false,
      zenOverlayDragOffsetX: 0,
      zenOverlayDragOffsetY: 0,
      treemapAnalysisLegendLeft: null,
      treemapAnalysisLegendTop: null,
      draggingTreemapAnalysisLegend: false,
      treemapAnalysisLegendDragOffsetX: 0,
      treemapAnalysisLegendDragOffsetY: 0,
      chartPanelWidth: 1080,
      chartPanelHeight: 760,
      chartPanelLeft: 16,
      chartPanelTop: 16,
      draggingChartPanelResize: false,
      chartPanelResizeStartX: 0,
      chartPanelResizeStartY: 0,
      chartPanelResizeStartWidth: 1080,
      chartPanelResizeStartHeight: 760,
      isDragging: false,
      dragMoved: false,
      lastPointerX: 0,
      lastPointerY: 0,
      devicePixelRatio: Math.max(1, window.devicePixelRatio || 1)
    };
}
